#mysql
spring:
  main:
    allow-circular-references: true
  application:
    name: business
  cloud:
    nacos:
      discovery:
        server-addr: 139.9.103.154:8848
    sentinel:
      transport:
        dashboard: 139.9.103.154:8180 # 指定sentinel控制台地址。
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.9.103.154:3306/javaplatform?useUnicode=true&characterEncoding=utf8
    username: root
    password:
# 失败回滚
#  transaction:
#    rollback-on-commit-failure: true
  #redis
  redis:
    database: 0
    host: 139.9.103.154
    port: 6379
    #    password: root
    timeout: 5000
    lettuce:
      pool:
        # 连接池最大连接数  (使用负值表示没有限制)
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 2
        # 连接池最大阻塞等待时间  (使用负值表示没有限制)
        max-wait: 2s


#mybatis-plus
mybatis-plus:
  mapper-locations: classpash:xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#sentinel 图形界面
management:
  endpoints:
    web:
      exposure:
        include: '*'
